x-common: &common
  volumes:
    - ./:/code
  working_dir: /code/template
  user: 1000:1000

services:
  api:
    <<: *common
    container_name: api
    image: oven/bun:1-alpine
    command: [sh, -c, bun --cwd api dev]
    ports:
      - 4000:4000
    environment:
      - FORCE_COLOR=1

  app:
    <<: *common
    depends_on:
      - api
    container_name: app
    image: imbios/bun-node:24-alpine
    command: [sh, -c, bun --cwd app dev --host 0.0.0.0]
    ports:
      - 5173:5173
    environment:
      - FORCE_COLOR=1
