name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore: release')
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@0a7b4175734cfea50c30b4317b1f9157dc7c1a75 # main

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Type check
        run: bun run check:types

      - name: Unit tests
        run: bun run test:coverage

      - name: Report coverage
        uses: davelosert/vitest-coverage-report-action@3c50566c523e04813df28de8f7c48dd97d663f1c # v2.11.2
        with:
          file-coverage-mode: all
          comment-on: none
  template-build-size-diff:
    name: Analyze template build size differences
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore: release')
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@0a7b4175734cfea50c30b4317b1f9157dc7c1a75 # main

      - name: Build template
        run: bun -F ./template build

      - name: Analyze template build size differences
        uses: kevinmarrec/workflows/filesize-diff@0a7b4175734cfea50c30b4317b1f9157dc7c1a75 # main
        with:
          directories: template/app/dist,template/api/dist
