name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    uses: kevinmarrec/workflows/.github/workflows/release.yml@de8a61d9c90d7dff252b9d40c7a0edb8b362bbca # main
    with:
      publish: true
      workflow-cleanup: ci.yml
    permissions:
      actions: write
      contents: write
      id-token: write
