name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    uses: kevinmarrec/workflows/.github/workflows/release.yml@c21981445f7b961592b4de2f65ba04e24afd4be8 # main
    with:
      publish: true
      workflow-cleanup: ci.yml
    permissions:
      actions: write
      contents: write
      id-token: write
